package lexico.auxiliares;

// Enumerado que recoge las acciones semanticas
// que puede llegar a ejecutar el analizador lexico
public enum Accion {
	LEER, 
	CONCATENAR, 
	DECLARAR_NUM, 
	INCREMENTAR_NUM,
	GENERAR_PR_ID,
	GENERAR_ENTERO,
	GENERAR_CADENA, 
	GENERAR_MENOS,
	GENERAR_AUTO_DEC, 
	GENERAR_IGUAL, 
	GENERAR_MAS,
	GENERAR_MAYOR,
	GENERAR_MENOR,
	GENERAR_NEGACION,
	GENERAR_COMA,
	GENERAR_PUNTO_COMA,
	GENERAR_PAR_AB,
	GENERAR_PAR_CE,
	GENERAR_LLA_AB,
	GENERAR_LLA_CE,
	ERR_CARACTER_NO_PERMITIDO,
	ERR_COMENTARIO_MAL_FORMADO,
	ERR_CADENA_NO_TERMINADA,
	ERR_CADENA_EN_VARIAS_LINEAS,
	TERMINAR_EJECUCION
}
